repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - "--no-sort-keys"
          - "--autofix"
      - id: mixed-line-ending

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.2
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - "--args=--module"
          - "--args=--force"
          - "--args=--config=__GIT_WORKING_DIR__/.tflint.hcl"
          - "--args=--disable-rule=aws_lambda_function_deprecated_runtime"
          - "--args=--disable-rule=terraform_module_pinned_source"
          - "--args=--disable-rule=terraform_deprecated_interpolation"
          - "--args=--disable-rule=terraform_unused_declarations"
          - "--args=--disable-rule=terraform_required_providers"
          - "--args=--disable-rule=terraform_typed_variables"
          - "--args=--disable-rule=terraform_deprecated_index"
      - id: terraform_validate
      - id: terraform_tfsec
        args:
          - "--args"
          - "--exclude-downloaded-modules"

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint

  - repo: local
    hooks:
      - id: check-json-files
        name: Check validity of JSON files and templates
        entry: scripts/check_json_files.sh
        language: script
